export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ERRORS = "ERRORS";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT = "PRODUCT";
export const SUCCESFULL_REGISTER = "SUCCESFULL_REGISTER";
export const FAILER_REGISTER = "FAILER_REGISTER";
export const AUTH_ERROR = "AUTH_ERROR";
